# This just checks the package can be installed using CUDA, no testing

trigger:
- master

pool:
  vmImage: 'ubuntu-22.04'
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- checkout: self
  submodules: true
  displayName: 'Checkout submodules'

- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- script: |
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
    sudo dpkg -i cuda-keyring_1.1-1_all.deb
    sudo apt-get update
    sudo apt-get -y install cuda-toolkit
  displayName: Install nvcc

- bash: conda env create --file environment.yml
  displayName: Create Anaconda environment and install dependencies

# to add C++ tests add the following line, and remove --no-cpp
# pushd src && make && make install && popd
- script: |
    source activate pp_env
    export PATH=${CUDA_HOME}/bin${PATH:+:${PATH}}
    export LD_LIBRARY_PATH=${CUDA_HOME}/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
    export SKETCHLIB_INSTALL=azure
    python -m pip install --no-deps --ignore-installed . -vvv
  displayName: 'Build & install (setup.py)'

- script: |
    source activate pp_env
    export PATH=${CUDA_HOME}/bin${PATH:+:${PATH}}
    export LD_LIBRARY_PATH=${CUDA_HOME}/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
    cd test && python run_test.py
  displayName: 'Run tests (run_test.py)'
