# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- checkout: self
  submodules: true
  displayName: 'Checkout submodules'

- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- bash: conda env create --quiet --file environment.yml
  displayName: Create Anaconda environment and install dependencies

- script: |
    source activate pp_env
    python -m pip install --no-deps --ignore-installed .
    ls /usr/share/miniconda/envs/pp_env/lib
    pushd src && make && make install && popd
    cd test && python run_test.py
  displayName: 'Install and run_test.py'
