name: pp_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - cmake >= 3.12
  - pybind11
  - zlib
  - eigen
  - highfive
  - hdf5
  - h5py
  - nlohmann_json
  - openblas
  - armadillo
  - libgfortran-ng
  - cudatoolkit
  - nvcc_linux-64
