name: pp_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - docopt
  - cmake >= 3.12
  - pybind11
  - zlib
  - eigen
  - highfive
  - hdf5 >= 1.14.3
  - h5py >= 3.10.0
  - nlohmann_json
  - openblas
  - libgfortran-ng
  - nvcc_linux-64
  - cudatoolkit==11.2 # This is pinned due to version install on azure, see azure-pipelines.yml
