{% set name = "pp_sketchlib" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/johnlees/{{ name|lower }}.git
  git_rev: v{{ version }}
  sha256: b1d2cd8b579d3b56192e673d6f69bbec3e31e3ebe5744c04ae864aee99cab0b5

build:
  number: 0
  skip: True  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - poppunk_sketch = pp_sketch.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - pybind11
    - zlib
    - bzip2
    - eigen
    - hdf5
    - lapack
    - openblas
  run:
    - python
    - numpy
    - zlib
    - bzip2
    - hdf5
    - h5py
    - lapack
    - openblas

test:
  imports:
    - pp_sketch
  commands:
    - poppunk_sketch --version

about:
   home: https://github.com/johnlees/pp-sketchlib
   license: Apache-2.0
   license_family: APACHE
   license_file: LICENSE
   summary: Library of sketching functions used by PopPUNK


extra:
   skip-lints:
     - uses_vcs_url
